<#
.SYNOPSIS
Validates recent telemetry ingestion for the Microsoft Sentinel SOC lab.

.DESCRIPTION
Checks the Log Analytics workspace for recent Windows Security and
PowerShell Operational events generated by LAB-WIN01.

The script is intended as a lightweight SOC lab health check.

Telemetry validated:
- SecurityEvent: Windows Security events
- Event: PowerShell Operational Event ID 4104
#>
